version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    depends_on:
      - rabbitmq
      - mongo
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      MONGO_URI: mongodb://mongo:27017
      MIN_PROCESSING_TIME: 2
      MAX_PROCESSING_TIME: 15
      TOXICITY_THRESHOLD: 70
    volumes:
      - ./app:/app/app
    ports: []

volumes:
  mongo_data:
